import type * as AnalysisModule from "../../pkg/generated/analysis/inspector-component";
import type * as GpuAnalysisInterfaceModule from "../../pkg/generated/gpu-analysis/interfaces/millipede-inspector-gpu-analysis";
import type * as GpuAnalysisAsyncInterfaceModule from "../../pkg/generated/gpu-analysis-async/interfaces/millipede-inspector-gpu-analysis-async";
import type * as GpuAnalysisFrameInterfaceModule from "../../pkg/generated/gpu-analysis-frame/interfaces/millipede-inspector-gpu-analysis-frame";
import type * as WasiAsyncProofsModule from "../../pkg/generated/wasi-0.3/inspector-component";

export type AnalysisInterface = typeof AnalysisModule.analysis;
export type AnalysisGeneratedModule = {
  /** Browser-safe analysis export generated by jco. */
  analysis?: AnalysisInterface;
};

export type GpuAnalysisInterface = typeof GpuAnalysisInterfaceModule;
export interface GpuAnalysisGeneratedModule {
  /** Stable GPU-analysis export generated by jco. */
  gpuAnalysis?: GpuAnalysisInterface;
}

export type GpuAnalysisAsyncInterface = typeof GpuAnalysisAsyncInterfaceModule;
export interface GpuAnalysisAsyncGeneratedModule {
  /** Chrome/JSPI-only async GPU-analysis export generated by jco. */
  gpuAnalysisAsync?: GpuAnalysisAsyncInterface;
}

export type GpuAnalysisFrameInterface = typeof GpuAnalysisFrameInterfaceModule;
export type GpuAnalysisFrameEncodedResult =
  GpuAnalysisFrameInterfaceModule.EncodedAnalysisFrame;
export interface GpuAnalysisFrameGeneratedModule {
  /** Scheduler-owned shared-frame GPU-analysis export generated by jco. */
  gpuAnalysisFrame?: GpuAnalysisFrameInterface;
}

type RawWasiAsyncProofsInterface = typeof WasiAsyncProofsModule.wasiAsyncProofs;
export type WasiAsyncProofsInterface = Omit<
  RawWasiAsyncProofsInterface,
  "proveStream"
> & {
  proveStream(label: string): Promise<AsyncIterable<number>>;
};
export type WasiAsyncProofsGeneratedModule = {
  /** Isolated WASI 0.3 async proof export generated by jco. */
  wasiAsyncProofs?: WasiAsyncProofsInterface;
};

export type NodeRecord = AnalysisModule.analysis.NodeRecord;
export type TreeStats = AnalysisModule.analysis.TreeStats;

/**
 * Import the jco-generated browser-safe analysis module.
 *
 * 1. Keeps `index.ts` independent from generated file layout details.
 * 2. Uses an extensionless authored TypeScript specifier.
 * 3. Lets the loader build rewrite the emitted runtime specifier to `.js`.
 *
 * @returns The generated analysis module namespace.
 */
export function importAnalysisGeneratedModule(): Promise<AnalysisGeneratedModule> {
  return import("../../pkg/generated/analysis/inspector-component");
}

/**
 * Import the jco-generated stable GPU-analysis module.
 *
 * 1. Keeps the stable GPU-analysis world behind the local generated adapter.
 * 2. Uses an extensionless authored TypeScript specifier.
 * 3. Lets the loader build rewrite the emitted runtime specifier to `.js`.
 *
 * @returns The generated stable GPU-analysis module namespace.
 */
export function importGpuAnalysisGeneratedModule(): Promise<GpuAnalysisGeneratedModule> {
  return import("../../pkg/generated/gpu-analysis/inspector-component");
}

/**
 * Import the jco-generated Chrome/JSPI-only GPU-analysis module.
 *
 * 1. Keeps the async GPU-analysis world behind the local generated adapter.
 * 2. Uses an extensionless authored TypeScript specifier.
 * 3. Lets the loader build rewrite the emitted runtime specifier to `.js`.
 *
 * @returns The generated async GPU-analysis module namespace.
 */
export function importGpuAnalysisAsyncGeneratedModule(): Promise<GpuAnalysisAsyncGeneratedModule> {
  return import("../../pkg/generated/gpu-analysis-async/inspector-component");
}

/**
 * Import the scheduler-owned shared-frame GPU-analysis module.
 *
 * The current compiled artifact has a distinct WIT world whose required import
 * surface omits encoder `finish` and `gpu-queue`. Borrowing alone does not
 * guarantee that restriction: the Rust ownership contract, host guard, and
 * component-boundary integration proof keep those imports absent. Keeping
 * this generated path separate lets the loader instantiate the frame world
 * lazily without coupling it to stable or JSPI module loading.
 *
 * @returns The generated shared-frame GPU-analysis module namespace.
 */
export function importGpuAnalysisFrameGeneratedModule(): Promise<GpuAnalysisFrameGeneratedModule> {
  return import("../../pkg/generated/gpu-analysis-frame/inspector-component");
}

/**
 * Import the jco-generated WASI 0.3 async proof module.
 *
 * 1. Keeps proof-only generated module layout out of the public loader.
 * 2. Uses an extensionless authored TypeScript specifier.
 * 3. Lets the loader build rewrite the emitted runtime specifier to `.js`.
 *
 * @returns The generated WASI async proof module namespace.
 */
export function importWasiAsyncProofsGeneratedModule(): Promise<WasiAsyncProofsGeneratedModule> {
  return import(
    "../../pkg/generated/wasi-0.3/inspector-component"
  ).then((module) => {
    const proofs = module.wasiAsyncProofs;
    return {
      wasiAsyncProofs: proofs
        ? {
            proveAsyncFunc: proofs.proveAsyncFunc,
            proveFuture: proofs.proveFuture,
            proveStream: async (label: string) => proofs.proveStream(label),
          }
        : undefined,
    };
  });
}
